version: '2'
services:
  gmi_netapp:
    # Name of the built image and of the future container
    image: gmi_netapp_img
    container_name: gmi_netapp_container
    # List of environment variables
    environment:
      NETAPP_NAME: "${netapp_name}"
      NETAPP_ID: "${netapp_id}"
      NETAPP_PORT_VAPP: "${netapp_port_vapp}" 
      NETAPP_PATH: "${netapp_path}"
      NEF_HOST: "${nef_host}"
      NEF_LOGIN: "${nef_login}"
      NEF_PWD: "${nef_pwd}"
      NEF_CALLBACK_URL: "${nef_callback_url}"
      CAPIF_HOST: "${capif_host}"
      CAPIF_HTTP_PORT: "${capif_http_port}"
      CAPIF_HTTPS_PORT: "${capif_https_port}"
      CAPIF_CALLBACK_URL: "${capif_callback_url}"  
      CAPIF_KEY_PATH: "${capif_key_path}"
      UE_REQUESTED_IP: "${ue_requested_ip}"
      
    build:
    # Path to the src code
      context: ./
      
    ports:
      # If port mapping is needed, left is host side and right is container side according to https://docs.docker.com/compose/compose-file/#ports
      # Be careful: if no mapping is specified, Docker will use a random available port on container side!
      - "8383:8383"

    extra_hosts:
      - "capifcore:10.161.1.117"
# network bridge with nef_emulator_default to be able to reach the NEF emulator 
#networks:
  #default:
    #name: nef_emulator_default
    #external: true
