version: '2'
services:
  gmi_netapp:
    # Name of the built image and of the future container
    image: gmi_netapp_img
    container_name: gmi_netapp_container
    # List of environment variables
    environment:
      NETAPP_NAME: "${netapp_name}"
      NETAPP_ID: "${netapp_id}"
      NETAPP_PORT_VAPP: "${netapp_port_vapp}" 
      NETAPP_PATH: "${netapp_path}"
      NEF_USER: "${nef_user}"
      NEF_PASSWORD: "${nef_password}"
      NEF_ADDRESS: "${nef_address}"
      NEF_CALLBACK_URL: "${nef_callback_url}"
      CAPIF_HOSTNAME: "${capif_hostname}"
      CAPIF_PORT_HTTP: "${capif_port_http}"
      CAPIF_PORT_HTTPS: "${capif_port_https}"
      CAPIF_CALLBACK_URL: "${capif_callback_url}"  
      PATH_TO_CERTS: "${path_to_certs}"
      UE_REQUESTED_IP: "${ue_requested_ip}"
      ENVIRONMENT_MODE: "${environment_mode}"
      
    build:
    # Path to the src code
      context: ./
      
    ports:
      # If port mapping is needed, left is host side and right is container side according to https://docs.docker.com/compose/compose-file/#ports
      # Be careful: if no mapping is specified, Docker will use a random available port on container side!
      - "8383:8383"

    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "capifcore:host-gateway" #Note: syntax without quotes not accepted => tester sans

# We need to create a network bridge with nef_emulator_default to be able to reach the NEF emulator 
# This works
networks:
  default:
    # name: nef_emulator_services_default
    name: services_default
    external: true
